add order-add-to-cart-api and unit test
SoniaChoo/online-store pull request #27
Opened 2020-02-19 07:26 UTC by SoniaChoo

2020-02-19 08:09 UTC, ziyitony commented on db/orders.go
> +	detail.Number += carts[0].Number
please add condition to judge if length is 1.

2020-02-19 08:19 UTC, ziyitony requested changes

2020-02-19 08:19 UTC, ziyitony commented on db/orders.go
> +	_, err = db.QueryContext(ctx, "insert into order_detail(detail_id, rest_id, order_id, dish_id, price, number, status) Values(?,?,?,?,?,?,?)", detail.DetailId, detail.RestId, detail.OrderId, detail.D
you don't have detail_id here, please update your sql

2020-02-19 08:19 UTC, ziyitony commented on db/orders.go
> +	if _, err = db.QueryContext(ctx, "update order_detail set number = ? where dish_id = ?", detail.Number, detail.DishId); err != nil {
please try to use PK if you have it.

2020-02-19 08:31 UTC, ziyitony commented on db/orders.go
> +	if err = UpdateDishFavorite(detail.Number, detail.DishId); err != nil {
the favorite count is not the same as detail.Number

2020-02-20 08:00 UTC, SoniaChoo commented on db/orders.go
> +	detail.Number += carts[0].Number
updated.

2020-02-20 08:04 UTC, SoniaChoo commented on db/orders.go
> +	_, err = db.QueryContext(ctx, "insert into order_detail(detail_id, rest_id, order_id, dish_id, price, number, status) Values(?,?,?,?,?,?,?)", detail.DetailId, detail.RestId, detail.OrderId, detail.D
updated.

2020-02-20 08:07 UTC, SoniaChoo commented on db/orders.go
> +	if _, err = db.QueryContext(ctx, "update order_detail set number = ? where dish_id = ?", detail.Number, detail.DishId); err != nil {
updated.

2020-02-20 08:39 UTC, SoniaChoo commented on db/orders.go
> +	if err = UpdateDishFavorite(detail.Number, detail.DishId); err != nil {
updated.

2020-02-20 15:05 UTC, merged